In [1]:
#1
#define a finction.Xinyi Wu explained to me what is asked in problem
def custom_operation(x,y,z):
     return x + y - 10 * z

def print_values(a,b,c):
    if a > b:
        if b > c:
# if a>b>c,output(a,b,c)
            result = custom_operation(a,b,c)
        else:
            if a > c:
# if a>c>=b，output(a,c,b)
                result = custom_operation(a,c,b)
            else:
# if c>=a>b,output(c,a,b)
                result = custom_operation(c,a,b)
# b>=a
    else:
        if b > c:
# if b>a,b>c
            result = custom_operation()
        else:
            result = custom_operation(c,b,a)
    print(result)
    
print_values(10,5,1)

5


In [3]:
# 2
#import math module,use the ceil function
import math
# def a function
def F(x): 
# if x=1,F(x)=1
    if x == 1:
        return 1
# if x≠1,return F(x)
    else:
        return F(math.ceil(x/3))+2*x
# creat a list
lst = [3,5,7,8,9]
# collect 
result_lst = []
for x in lst:
    result_lst.append(F(x))
print(result_lst)

[7, 15, 21, 23, 25]


In [7]:
#3.1
def Find_number_of_ways(x):
    
    counts=0

    for a in range(1,7):
        for b in range(1,7):
            for c in range(1,7):
                for d in range(1,7):
                    for e in range(1,7):
                        for f in range(1,7):
                            for g in range(1,7):
                                for h in range(1,7):
                                    for i in range(1,7):
                                        for j in range(1,7):
                                            sum=a+b+c+d+e+f+g+h+i+j
                                            if sum==x:
                                                counts += 1
    return counts
x=11

C=Find_number_of_ways(x)
print(C)

1


In [14]:
#3.2
def Find_number_of_ways(x):
    
    counts=0

    for a in range(1,7):
        for b in range(1,7):
            for c in range(1,7):
                for d in range(1,7):
                    for e in range(1,7):
                        for f in range(1,7):
                            for g in range(1,7):
                                for h in range(1,7):
                                    for i in range(1,7):
                                        for j in range(1,7):
                                            sum=a+b+c+d+e+f+g+h+i+j
                                            if sum==x:
                                                counts += 1
    return counts

Number_of_ways=[]

for x in range(10,61):
    Number_of_ways.append(Find_number_of_ways(x))
print(Number_of_ways)

max_Number_of_ways=max(Number_of_ways)
print(max_Number_of_ways)

[1, 10, 55, 220, 715, 2002, 4995, 11340, 23760, 46420, 85228, 147940, 243925, 383470, 576565, 831204, 1151370, 1535040, 1972630, 2446300, 2930455, 3393610, 3801535, 4121260, 4325310, 4395456, 4325310, 4121260, 3801535, 3393610, 2930455, 2446300, 1972630, 1535040, 1151370, 831204, 576565, 383470, 243925, 147940, 85228, 46420, 23760, 11340, 4995, 2002, 715, 220, 55, 10, 1]
4395456


In [9]:
#4.1
#导入random模版
import random
#定义一个随机函数
def random_integer(N):
    #制造一个集合进行收集
    random_int=[]
    #在1到10的范围内取值，并且包含1和10
    for _ in range(N):
        
        number=random.randint(1,10)
        #将生成的数值添加到random_int这个列表的末尾
        random_int.append(number)
    #放入集合中收集起来
    return random_int
#旷金佩explained to me what is asked in problem 
N=3
H=random_integer(N)
print(H)

[1, 1, 9]


In [1]:
#4.2
from itertools import combinations

def sum_averages(lst):
    total_sum=0.0
    counts=0
    n=len(lst)
    for i in range (1,1+n):
         for subset in combinations (lst , i):
             average=sum(subset)/len(subset)
             total_sum+=average
             counts+=1
    return total_sum

result=sum_averages([1,2,3])
print(result)

14.0


In [35]:
#4.3
#导入matplotlib模版进行绘图


from itertools import combinations

def sum_averages(lst):
    total_sum=0.0
    counts=0
    n=len(lst)
    for i in range (1,1+n):
         for subset in combinations (lst , i):
             
             average=sum(subset)/len(subset)
             
             total_sum += average
             
             counts+=1
             
    return total_sum


#导入matplotlib模块
import matplotlib.pyplot as plt

Total_sum_averages=[]

for N in range (1,101):
    #导入random模块
    import random
    
    array=[random.randint(0,10) for _ in range (N)]
    
    Total_sum_averages.append(sum_averages(array))
    
#绘制图
plt.plot (Total_sum_averages)
#x轴
plt.xlabel('N')
#y轴
plt.ylabel('sum of averages')
#图像标题
plt.title('sum of averages of all subsets for N=1 to 100')

plt.show()

TypeError: 'int' object is not callable

In [39]:
#5.1
#导入numpy模块
import numpy as np

def creat_matrix(N,M):
    
    matrix = np.zeros((N , M) , dtype=int)
    
    matrix[0,0] = 1
    
    matrix[N-1,M-1] = 1
    
    for i in range(1,N-1):
        for j in range (1,M-1):
            matrix[i,j] = np.random.randint(0,2)
    return matrix

N=5
M=5
matrix=creat_matrix(N,M)
print(matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 1]]


In [44]:
#5.2
def Count_path(grid):
    #如果grid是是空的或者不是列表，将没有网格可以计算路径;或者grid的一行或者第一个元素为0，也没有计算路径。
    if not grid or not grid[0]:
        return 0
    #计算grid的行数
    rows=len(grid)
    #grid[0]表示grid的第一行，计算第一行的个数，即计算grid的列数
    cols=len(grid[0])
    #如果grid的第一行第一个元素为0或者grid最后一行最后一个元素为0，即起点与终点为0，那么返回0
    if grid[0][0]==0 or grid[rows-1][cols-1]==0:
        return 0
    #初始化矩阵，创造一个全为0，数量为cols的列表作为一行，循环rows次，就生成rows行
    matrix=[[0]*cols for _ in range(rows)]
    #定义这个矩阵的起点为1
    matrix[0][0]=1
    
    for i in range(rows):
        for j in range(cols):
           if  grid[i][j] == 1:
               #如果当前单元格不在第一行，即可以从上方的单元格像下到达该单元格
               if i >0 :
                   #那么当前单元格的路径数量就是上方单元格的路径数量+1
                   matrix[i][j]+=matrix[i-1][j]
               #如果可以从左边到达，即左边的单元格向右移动到达该单元格
               if j >0:
                   matrix[i][j]+=matrix[i][j-1]
    #最终到达右下角单元格的路径数量
    return matrix[rows-1][cols-1]
 
grid=[[1,1,0],
      [1,1,1],
      [0,1,1]
      ]
print(Count_path(grid))

4


In [47]:
#5.3
import numpy as np
#创建一个N×M的矩阵
def creat_matrix(N, M):
    #matrix在左上角与右下角生成1.其他地方随机生成0或1
    matrix = np.random.randint(0, 2, size=(N, M))
    
    matrix[0][0] = 1
    matrix[N-1][M-1] = 1
    return matrix
#计算路径
def count_paths(matrix):
    #找出N和M值
    N = len(matrix)
    M = len(matrix[0])
#创建一个dp表来存储路径数,在表中的都是整数
    dp = np.zeros((N,M),dtype = int)
    #如果matrix的左上角单元格数值为1，则证明可行，那么动态规划表左上角单元格为1，否则为0
    if matrix[0][0] == 1:
        dp[0][0] = 1
    else:
        dp[0][0]=0
    #对dp动态规划表进行计算
    for i in range(N):
        for j in range(M):
            if matrix[i][j] == 1:
                if i > 0:
                    dp[i][j] += dp[i-1][j]
                if j > 0:
                    dp[i][j] += dp[i][j-i]
    # 返回右下角的总路径数              
    return dp[N-1][M-1]
#计算路径数的平均数
def average_paths(N, M, lops):
    total_paths = 0
    for _ in range (lops):
        matrix = creat_matrix(N, M)
        total_paths += count_paths(matrix)
    return total_paths/lops

N=10
M=8
lops=1000
aver_paths = average_paths(N, M, lops)
print(aver_paths)

0.018
